[profile.default]
version = "0.8.20"
optimizer = true
optimizer_runs = 1000
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@solmate-utils/=lib/solmate/src/utils/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@rocketpool/contracts/=lib/rocketpool/contracts/",
    "@rocketpool-router/contracts/=lib/rocketpool-router/contracts/",
]
gas_reports = ["*"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
